### ISSUE TITLE
where's our star?

### ISSUE THREAD

**Issue by ameliejyc** [eliasmalik/pabx-redux-middleware#1]
@eliascodes you promised to star dickhub on friday 26th jan and we are still waiting.

link [here](https://github.com/astroash/dickhub) for your convenience.

**Comment by eliasmalik** [comment]
This is outrageous. Take your star and be gone.

<img width="889" alt="screen shot 2018-01-27 at 18 06 12" src="https://user-images.githubusercontent.com/12719553/35474908-e06cb236-038c-11e8-8ebb-6d2138efb35e.png">
